// ملف data.js

// ===================================
// قائمة السور (114 سورة)
// تم إضافة خاصية 'id' لطباعة رقم السورة
// ===================================
const allSurahs = [
    { id: 1, name: "الفاتحة", startPage: 1 },
    { id: 2, name: "البقرة", startPage: 2 },
    { id: 3, name: "آل عمران", startPage: 50 },
    { id: 4, name: "النساء", startPage: 77 },
    { id: 5, name: "المائدة", startPage: 106 },
    { id: 6, name: "الأنعام", startPage: 128 },
    { id: 7, name: "الأعراف", startPage: 151 },
    { id: 8, name: "الأنفال", startPage: 177 },
    { id: 9, name: "التوبة", startPage: 187 },
    { id: 10, name: "يونس", startPage: 208 },
    { id: 11, name: "هود", startPage: 221 },
    { id: 12, name: "يوسف", startPage: 235 },
    { id: 13, name: "الرعد", startPage: 249 },
    { id: 14, name: "إبراهيم", startPage: 255 },
    { id: 15, name: "الحجر", startPage: 262 },
    { id: 16, name: "النحل", startPage: 267 },
    { id: 17, name: "الإسراء", startPage: 282 },
    { id: 18, name: "الكهف", startPage: 293 },
    { id: 19, name: "مريم", startPage: 305 },
    { id: 20, name: "طه", startPage: 312 },
    { id: 21, name: "الأنبياء", startPage: 322 },
    { id: 22, name: "الحج", startPage: 332 },
    { id: 23, name: "المؤمنون", startPage: 342 },
    { id: 24, name: "النور", startPage: 350 },
    { id: 25, name: "الفرقان", startPage: 359 },
    { id: 26, name: "الشعراء", startPage: 367 },
    { id: 27, name: "النمل", startPage: 377 },
    { id: 28, name: "القصص", startPage: 385 },
    { id: 29, name: "العنكبوت", startPage: 396 },
    { id: 30, name: "الروم", startPage: 404 },
    { id: 31, name: "لقمان", startPage: 411 },
    { id: 32, name: "السجدة", startPage: 415 },
    { id: 33, name: "الأحزاب", startPage: 418 },
    { id: 34, name: "سبأ", startPage: 428 },
    { id: 35, name: "فاطر", startPage: 434 },
    { id: 36, name: "يس", startPage: 440 },
    { id: 37, name: "الصافات", startPage: 446 },
    { id: 38, name: "ص", startPage: 453 },
    { id: 39, name: "الزمر", startPage: 458 },
    { id: 40, name: "غافر", startPage: 467 },
    { id: 41, name: "فصلت", startPage: 477 },
    { id: 42, name: "الشورى", startPage: 483 },
    { id: 43, name: "الزخرف", startPage: 489 },
    { id: 44, name: "الدخان", startPage: 496 },
    { id: 45, name: "الجاثية", startPage: 499 },
    { id: 46, name: "الأحقاف", startPage: 502 },
    { id: 47, name: "محمد", startPage: 507 },
    { id: 48, name: "الفتح", startPage: 511 },
    { id: 49, name: "الحجرات", startPage: 515 },
    { id: 50, name: "ق", startPage: 518 },
    { id: 51, name: "الذاريات", startPage: 520 },
    { id: 52, name: "الطور", startPage: 523 },
    { id: 53, name: "النجم", startPage: 526 },
    { id: 54, name: "القمر", startPage: 528 },
    { id: 55, name: "الرحمن", startPage: 531 },
    { id: 56, name: "الواقعة", startPage: 534 },
    { id: 57, name: "الحديد", startPage: 537 },
    { id: 58, name: "المجادلة", startPage: 542 },
    { id: 59, name: "الحشر", startPage: 545 },
    { id: 60, name: "الممتحنة", startPage: 549 },
    { id: 61, name: "الصف", startPage: 551 },
    { id: 62, name: "الجمعة", startPage: 553 },
    { id: 63, name: "المنافقون", startPage: 554 },
    { id: 64, name: "التغابن", startPage: 556 },
    { id: 65, name: "الطلاق", startPage: 558 },
    { id: 66, name: "التحريم", startPage: 560 },
    { id: 67, name: "الملك", startPage: 562 },
    { id: 68, name: "القلم", startPage: 564 },
    { id: 69, name: "الحاقة", startPage: 566 },
    { id: 70, name: "المعارج", startPage: 568 },
    { id: 71, name: "نوح", startPage: 570 },
    { id: 72, name: "الجن", startPage: 572 },
    { id: 73, name: "المزمل", startPage: 574 },
    { id: 74, name: "المدثر", startPage: 575 },
    { id: 75, name: "القيامة", startPage: 577 },
    { id: 76, name: "الإنسان", startPage: 578 },
    { id: 77, name: "المرسلات", startPage: 580 },
    { id: 78, name: "النبأ", startPage: 582 },
    { id: 79, name: "النازعات", startPage: 583 },
    { id: 80, name: "عبس", startPage: 585 },
    { id: 81, name: "التكوير", startPage: 586 },
    { id: 82, name: "الانفطار", startPage: 587 },
    { id: 83, name: "المطففين", startPage: 587 },
    { id: 84, name: "الانشقاق", startPage: 589 },
    { id: 85, name: "البروج", startPage: 590 },
    { id: 86, name: "الطارق", startPage: 591 },
    { id: 87, name: "الأعلى", startPage: 591 },
    { id: 88, name: "الغاشية", startPage: 592 },
    { id: 89, name: "الفجر", startPage: 593 },
    { id: 90, name: "البلد", startPage: 594 },
    { id: 91, name: "الشمس", startPage: 595 },
    { id: 92, name: "الليل", startPage: 595 },
    { id: 93, name: "الضحى", startPage: 596 },
    { id: 94, name: "الشرح", startPage: 596 },
    { id: 95, name: "التين", startPage: 597 },
    { id: 96, name: "العلق", startPage: 597 },
    { id: 97, name: "القدر", startPage: 598 },
    { id: 98, name: "البينة", startPage: 598 },
    { id: 99, name: "الزلزلة", startPage: 599 },
    { id: 100, name: "العاديات", startPage: 599 },
    { id: 101, name: "القارعة", startPage: 600 },
    { id: 102, name: "التكاثر", startPage: 600 },
    { id: 103, name: "العصر", startPage: 601 },
    { id: 104, name: "الهمزة", startPage: 601 },
    { id: 105, name: "الفيل", startPage: 601 },
    { id: 106, name: "قريش", startPage: 602 },
    { id: 107, name: "الماعون", startPage: 602 },
    { id: 108, name: "الكوثر", startPage: 602 },
    { id: 109, name: "الكافرون", startPage: 603 },
    { id: 110, name: "النصر", startPage: 603 },
    { id: 111, name: "المسد", startPage: 603 },
    { id: 112, name: "الإخلاص", startPage: 604 },
    { id: 113, name: "الفلق", startPage: 604 },
    { id: 114, name: "الناس", startPage: 604 }
];

// ===================================
// قائمة الأجزاء (30 جزء)
// لا تحتاج لتعديل إضافي
// ===================================
const allJuz = [
    { name: "الجزء 1", startPage: 1 },
    { name: "الجزء 2", startPage: 22 },
    { name: "الجزء 3", startPage: 42 },
    { name: "الجزء 4", startPage: 62 },
    { name: "الجزء 5", startPage: 82 },
    { name: "الجزء 6", startPage: 102 },
    { name: "الجزء 7", startPage: 121 },
    { name: "الجزء 8", startPage: 142 },
    { name: "الجزء 9", startPage: 162 },
    { name: "الجزء 10", startPage: 182 },
    { name: "الجزء 11", startPage: 201 },
    { name: "الجزء 12", startPage: 222 },
    { name: "الجزء 13", startPage: 242 },
    { name: "الجزء 14", startPage: 262 },
    { name: "الجزء 15", startPage: 282 },
    { name: "الجزء 16", startPage: 302 },
    { name: "الجزء 17", startPage: 322 },
    { name: "الجزء 18", startPage: 342 },
    { name: "الجزء 19", startPage: 362 },
    { name: "الجزء 20", startPage: 382 },
    { name: "الجزء 21", startPage: 402 },
    { name: "الجزء 22", startPage: 422 },
    { name: "الجزء 23", startPage: 442 },
    { name: "الجزء 24", startPage: 462 },
    { name: "الجزء 25", startPage: 482 },
    { name: "الجزء 26", startPage: 502 },
    { name: "الجزء 27", startPage: 522 },
    { name: "الجزء 28", startPage: 542 },
    { name: "الجزء 29", startPage: 562 },
    { name: "الجزء 30", startPage: 582 }
];